### ISSUE TITLE
There are differences between demo5_b34e and demo5_b34i in the analysis of obs observation data

### ISSUE THREAD

**Issue by joseph-chunhui** [rtklibexplorer/RTKLIB#390]
[obs.zip](https://github.com/user-attachments/files/15981186/obs.zip)
OBS observation data is analyzed with demo5_b34e, showing that there is a cycle jump in GPS 2W, while analyzing the same file with demo5_b34i shows no cycle jump. What is the reason?
demo5_b34e
![微信截图_20240625113442](https://github.com/rtklibexplorer/RTKLIB/assets/169507953/5835eeca-f8be-45a6-9dd0-e77349cebdd3)
demo5_b34i
![微信截图_20240625113527](https://github.com/rtklibexplorer/RTKLIB/assets/169507953/d8452240-6124-48a0-84af-b0fae6d148ea)

**Comment by rtklibexplorer** [comment]
To see cycle slips in the observation file as reported by the receiver, the Cycle-Slip option in RTKPLOT should be set to "LLI Flag".  This is the most common setting for this option and when used for your sample file does not indicate cycle slips when using either the b34e or b34i versions of RTKPLOT.  If the Cycle-Slip option is set to "LLG" as you have done in your screenshots , RTKPLOT uses dual frequency geometry free linear combination to detect cycle-slips rather than using the receiver flags in the observation file.  I have not used this option before but from your screenshots it appears that there was a bug in the 34e code that has been fixed in the b34i code.  I don't know exactly which change to the code would have fixed this.
