### ISSUE TITLE
demo5 b33d & b33e rtkpost executables for win10 not scaling correctly

### ISSUE THREAD

**Issue by rchjhnsn** [rtklibexplorer/RTKLIB#74]
The window for the app clips such that controls at top and bottom are not visible or accessible. For example, the row of controls including the Options... button does not display nor is there a vertical scroll bar available to scroll the row into view. As a consequence,  doing ppk in demo5 b33d or b33e with rtklib using Win10 doesn't seem possible except via command line. 

Furthermore, the rtkpost window is too small on high-dpi (4k) displays. The font size looks to be about 1-2 pt, whereas on a 1080p monitor they're 4 pt or so (which in itself is too small). 

For both these issues, the executable for rtkconv displays correctly in Win10, as does the non-demo5 rtkpost executable.

These comments apply to Win10 2H2, but changing Compatibility of the exe in Properties doesn't seem to help.

**Comment by rtklibexplorer** [comment]
I believe this is the same as issue #48 and can be fixed with Windows scaling as described in that issue.  I also believe that some of the changes imported from the 2.4.3 b34 RTKLIB code may more directly address this issue.  Let me know if you still see a problem after trying the b34a code and the fix suggested in #48 and I will reopen this issue.
